export const READ_EXAMPLES = 'ADD_EXAMPLES';
export const EXAMPLES_FAILED = 'EXAMPLES_FAILED';
export const EXAMPLES_LOADING = 'EXAMPLES_LOADING';
export const READ_EXAMPLE = 'ADD_EXAMPLE';
export const POST_EXAMPLE = 'POST_EXAMPLE';
export const DELETE_EXAMPLE = 'DELETE_EXAMPLES'
// examples

//CHALLENGE
export const DISPLAY_MODAL = 'DISPLAY_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'