export const READ_EXAMPLES = "ADD_EXAMPLES";
export const EXAMPLES_FAILED = "EXAMPLES_FAILED";
export const EXAMPLES_LOADING = "EXAMPLES_LOADING";
export const READ_EXAMPLE = "ADD_EXAMPLE";
export const POST_EXAMPLE = "POST_EXAMPLE";
export const DELETE_EXAMPLE = "DELETE_EXAMPLES";
// examples

//CHALLENGE
export const DISPLAY_MODAL = "DISPLAY_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";
export const BEGIN_CHALLENGE = "BEGIN_CHALLENGE";
export const COMPLETE_CHALLENGE = "COMPLETE_CHALLENGE";
export const BACK_MODALINFOCHALLENGE = "BACK_MODALINFOCHALLENGE";

//Modal Create Challenge
export const NEXTPAGE_MODALCREATECHALLENGE = "NEXTPAGE_MODALCREATECHALLENGE";
export const BACKPAGE_MODALCREATECHALLENGE = "BACKPAGE_MODALCREATECHALLENGE";
export const RESETPAGE_MODALCREATECHALLENGE = "RESETPAGE_MODALCREATECHALLENGE";
